### ISSUE TITLE
Works on thinkpad x1c 2020 gen8 Gentoo

### ISSUE THREAD

**Issue by dearfl** [xmm7360/xmm7360-pci#103]
OS: Gentoo Linux(nomultilib)
kernel: Linux gentoo-kernel-bin 5.10.33

Country: CN
APN: bjlenovo12.njm2mapn
default pin: 1234

PS: The command `make` will success but `make load` will run into `segmentation fault` error. I resolve this by `make install` and reboot, then it all works fine.

**Comment by tgxn** [comment]
Good to hear, Will add `Gentoo` to DEVICES.md
