### ISSUE TITLE
Works ThinkPad L15 (Gen1)

### ISSUE THREAD

**Issue by joseangelmartinez** [xmm7360/xmm7360-pci#119]
Works fine on Lenovo ThinkPad L15 (Gen1)
Secure boot OFF
Need to remove SIM pin. Used an Android phone for that. Settings ⇾ Security ⇾ Ask for pin ⇾ NO
Not needed to set nameserver

**Comment by DHaussermann** [comment]
*@DHaussermann attached a* [message](https://dkh-local.ngrok.io/_redirect/pl/8auf5deg4fbauqryuga1sc38mr) *from @DHaussermann*

Pony :pony

**Comment by tgxn** [comment]
What OS?

**Comment by joseangelmartinez** [comment]
KDE Neon 20.04

2 ago. 2021 3:09:16 Domenic Horner ***@***.***>:
