### ISSUE TITLE
Works on Thinkpad X1 Nano (Ubuntu 21.04)

### ISSUE THREAD

**Issue by t11c** [xmm7360/xmm7360-pci#125]
It works, but
  * it stops after suspend/sleep --> have to reboot the machine everytime (don't know what else to do, there must be a better way)
  * it doesn't if there are any wifi networks connected

Thanks all devs! this has helped me a lot when traveling in places without wifi.

**Comment by tgxn** [comment]
#1 is known suspend/resume non-existent.

We should add information that this may fail if you have WiFi enabled/connected?

**Comment by tgxn** [comment]
Assigning to me to add you to `devices.md`
