### ISSUE TITLE
Works on ThinkPad X1 Yoga gen 4 / Pop_OS 20.04

### ISSUE THREAD

**Issue by Figureix** [xmm7360/xmm7360-pci#126]
Linux Kernel: 5.11.0-7620-generic
Carrier: TMobile/Google-Fi

Currently working on getting wwan to show in GUI (example/perl scripts). 

Awesome work here! In my free time I'm going to give a shot at figuring out power/sleep states...

**Comment by tgxn** [comment]
Thanks! Looking forward to any contributions :)

Assigning this to me to add `Yoga G4/Pop OS` to `DEVICES.md`
