### ISSUE TITLE
Unable to activate NordVPN while using LTE

### ISSUE THREAD

**Issue by jeff-tor** [xmm7360/xmm7360-pci#146]
When wifi is turned off/on
after keying in : lte on
I tried to connect to VPN using LTE

so I typed in terminal: nordvpn status
and received: "Please check your internet connection and try again."

maybe the connection needs to be recognized as wifi or something, sorry for the description

**Comment by tgxn** [comment]
hey @jeff-tor what did you get when you ran the commands? Did you see if there was any connectivity before activating your VPN?

**Comment by jeff-tor** [comment]
Hi tgxn sorry for the late response.. As far as I can remember: I remember I was able to access internet without VPN.

For example:

I ran "lte on" on the terminal, 
and immediately after that I ran "nordvpn c" for connecting, 
and it returns "Please check your internet connection and try again.", 

so I ran "nordvpn status" to just check if it's already running or something, 
it also showed "Please check your internet connection and try again."

but as of 27th feb 2022 I'm back on windows 10 due to work requirements.. I'll probably install linux again and re-visit this project at a later time ~
