### ISSUE TITLE
NOT AN ISSUE - Work very well on X390

### ISSUE THREAD

**Issue by ronylicha** [xmm7360/xmm7360-pci#17]
Just a little update, it's working like a charm on my x390 on ubuntu 19.10, just have to add nameserver to resol.conf.
i wrote a little bash script to connect every time i need, and disable/enable the wifi.

**Comment by Texas-C** [comment]
Works well on `X390` too!

Environment: Archlinux + X390

And I didn't add any nameserver. Just followed with `README.md` and used `sudo make load`

**Comment by isolosun** [comment]
gentoo x390, works well;
nice work;
