### ISSUE TITLE
ThinkPad P52s Working

### ISSUE THREAD

**Issue by cocide** [xmm7360/xmm7360-pci#19]
I can confirm this works very well on a P52s w/ Ubuntu 19.04. I did have to run the script twice and manually assign DNS.

The first time it ended with:
`INFO:root:IP address: 0.0.0.0, 0.0.0.0, 0.0.0.0
INFO:root:DNS server(s): 
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 88, in <module>
    address=ip_addr)
NameError: name 'ip_addr' is not defined`

The second time it assigned an IP, but I did have to add DNS via `resolvectl dns wwan0 8.8.8.8`

**Comment by enzingerm** [comment]
For me the error doesn't appear when programmatically retrying to get an IP adress if the first time it was zero. I created a hacky pull request which just does that and works for me, maybe anyone else can make use of it (#26)
