### ISSUE TITLE
Fedora Silverblue works!

### ISSUE THREAD

**Issue by aleksasiriski** [xmm7360/xmm7360-pci#206]
Just leaving this short tutorial for Fedora Silverblue, tested with Thinkpad T14 and T14s.

https://gist.github.com/aleksasiriski/aef30c6b03785277c8f7a79a472b97c9

**Comment by matijakljajic** [comment]
During testing, 2 out of 3 SIMs that are from different ISPs seem to have problems. They won't connect and keep displaying "Activation of network connection failed" error. Will update if I find a solution.
