### ISSUE TITLE
Signal level / access technology status reading

### ISSUE THREAD

**Issue by chemeris** [xmm7360/xmm7360-pci#22]
Sorry if this is an obvious question, but is there a way to read the signal level and used access technology (3G/4G/etc) from the driver?

**Comment by c3r34lk1ll3r** [comment]
In theory, you can access this information using AT interface.

For example,
`echo 'AT+CSQ?' | sudo tee /dev/ttyXMM1`

should return the signal quality.

`echo 'AT+COPS?' | sudo tee /dev/ttyXMM1`

should return the details about the connection ([here](https://m2msupport.net/m2msupport/atcops-plmn-selection/) you can find how to read the value ).

`AT+CLAC` will print all the command supported (although, it seems that not all are working).

**Comment by chemeris** [comment]
Thank you, makes sense (=works!).
