### ISSUE TITLE
No module named 'rpc_call_ids'

### ISSUE THREAD

**Issue by J0n4t4n** [xmm7360/xmm7360-pci#3]
Thanks for the work on this driver.
I wanted to test it out but I ran into the following issue.
After cloning I run `make && make load` and it works perfectly, I even already have a wwan0 interface after that.
Then I want to run the open_xdatachannel.py but I get the following error:

```
$ sudo python3 rpc/open_xdatachannel.py
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 3, in <module>
    import rpc
  File "/home/jonatan/xmm7360-pci/rpc/rpc.py", line 10, in <module>
    import rpc_call_ids
ModuleNotFoundError: No module named 'rpc_call_ids'
```

I'm using Arch Linux and Python 3.8.1.
I'm happy to continue testing this driver on my device, if I can get it to execute :)

**Comment by abrasive** [comment]
Whoops, somehow in my refactoring I forgot to add this file! My apologies, fixed now (:
