### ISSUE TITLE
Can't build on Manjaro Linux

### ISSUE THREAD

**Issue by random1st** [xmm7360/xmm7360-pci#38]
➜ make 
make -C /lib/modules/5.6.11-1-MANJARO/build M=/home/user/xmm7360-pci modules
make[1]: Entering directory '/usr/lib/modules/5.6.11-1-MANJARO/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.6.11-1-MANJARO/build'
make: *** [Makefile:9: default] Error 2

**Comment by udithvb** [comment]
Did you install the linux-headers for your kernel ? 

If not so then,
`sudo pacman -S linux*version*-headers` should fix it.

**Comment by tgxn** [comment]
did you make any progress on this @random1st ?

**Comment by tgxn** [comment]
Closing as stale, if there are still problems, please create a new issue!
