### ISSUE TITLE
ModemManager integration

### ISSUE THREAD

**Issue by enzingerm** [xmm7360/xmm7360-pci#4]
This is just a pointer to a discussion on the ModemManager-devel list at [0] where a Fibocom engineer planned to add support for L860-GL/L850-GL into ModemManager. Some thoughts revolved around faking a MBIM USB device which could easily be recognized by ModemManager, but I'm not sure whether this is the right approach.

[0] https://www.mail-archive.com/modemmanager-devel@lists.freedesktop.org/msg05012.html

**Comment by wicadmin** [comment]
Doesn't seem this was done.

**Comment by tgxn** [comment]
Got the wrong PR :)
