### ISSUE TITLE
Works on opensuse leap 15.2 and Lenovo T495

### ISSUE THREAD

**Issue by gariac** [xmm7360/xmm7360-pci#51]
When I bought the T495, to get the extra bright screen the cellular modem was a mandatory upgrade. Thank you for making it actually work.

I will say that all I have managed to do is use the fibocom for sftp and ssh since I don't understand how to add the DNS. However I am working on running the ModemManager which should make this more automatic.

https://github.com/enzingerm/ModemManager

Opensuse LEAP 15.2
Linux 5.3.18-lp152.41-default #1 SMP Thu Sep 3 23:02:59 UTC 2020 (a4d139b) x86_64 x86_64 x86_64 GNU/Linux

Note the reply about adding the headers came in useful. In opensuse they are added with yast.

**Comment by tgxn** [comment]
I'll be looking to merge MM support soon https://github.com/xmm7360/xmm7360-pci/pull/66
