### ISSUE TITLE
Works on Lenovo T14s AMD Manjaro 20.1.2

### ISSUE THREAD

**Issue by yoxcu** [xmm7360/xmm7360-pci#54]
[second_try.log](https://github.com/xmm7360/xmm7360-pci/files/5432979/second_try.log)
[fist_try.log](https://github.com/xmm7360/xmm7360-pci/files/5432980/fist_try.log)

Managed to compile it after installing linux-headers and pyroute2. Using a Telecom SIM and disabled WLAN interface.
First execution throws a exception:

```
NFO:root:IP address: 0.0.0.0, 0.0.0.0, 0.0.0.0
INFO:root:DNS server(s): 
0.0.0.0
0.0.0.0
0.0.0.0
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 89, in <module>
    address=ip_addr)
NameError: name 'ip_addr' is not defined

```
but waiting a few seconds the script runs fine and i get a wwan0 interface with an ip-adress along with a working connection!

attached logs of first and second try.

Thanks for the awesome work!

**Comment by yoxcu** [comment]
#26 solved the issue of executing the script twice
worked on both 5.8 and 5.9 kernel

**Comment by ItanVazlak** [comment]
good day.

I am a novice Linux user. I could not independently install this driver on Lenovo T480s and Manjaro.

Can you help me and write here a sequence of commands in the terminal for Manjaro?

I have installed all the packages I need, but when I run the "make && make load" command, I get an error:

"make [1]: Entering directory '/usr/lib/modules/5.10.42-1-MANJARO/build'
make [1]: *** No rule to make target 'modules'. Stop.
make [1]: Leaving directory '/usr/lib/modules/5.10.42-1-MANJARO/build'
make: *** [Makefile: 9: default] Error 2
"

**Comment by tgxn** [comment]
@ItanVazlak G'day, It looks like you might not have kernel headers installed, 

You could try an article like [this](https://linuxconfig.org/manjaro-linux-kernel-headers-installation) one.

**Comment by yoxcu** [comment]
Hi,

make sure you have the (right version) of kernel-headers installed!

`sudo pacman -S linux-headers`
should do the trick!

If installing through pamac (gui) search for the the right version. For you it should be
`linux510-headers`
according to your log.
