### ISSUE TITLE
Delay while shutdown (EliteBook x360 830 G7 w/ Fedora 33 beta)

### ISSUE THREAD

**Issue by TomPortman** [xmm7360/xmm7360-pci#55]
Hello,

First of all thank you very much for your work. I managed to make my XMM7360 work on an EliteBook x360 830 G7 running Fedora 33 beta (although I had to disable secure boot in the BIOS because of the kernel lockdown).

My problem is that when trying to shut down the system (GNOME3), it takes much more time once the WWAN connection has been configured ("open_xdatachannel.py" command issued) compared to when it has not been configured (no "open_xdatachannel.py" command issued). I tried to just unload the module prior to shutting down the system, but this does not help.

Do you have any suggestion on how to obtain a speedy shutdown once the module is in use?

Thank you in advance and best regards

Tom

**Comment by tgxn** [comment]
Hey @TomPortman I think this might be related to the current absence of any suspend/resume handling. (#1)

I'm not sure what might be causing this delay, but without any system logs it's going to be hard to drill into the issue further.

I'm going to close this issue now, but please re-open it if you would like! :)
