### ISSUE TITLE
Initialisation errors

### ISSUE THREAD

**Issue by Matriciel** [xmm7360/xmm7360-pci#57]
Hi,
I have a xmm7560 on a HP Elitebook.
I have successfully compiled the driver and loaded it.
When i launch open`_xdatachannel.py` with apn, i don't have IP address and uncessfull initialisation:

`RPC executing UtaMsSmsInit
b'1600000002040000001602040000003011000100020400000000'
response: 0x0
RPC executing UtaMsCbsInit
b'1600000002040000001602040000002511000100020400000000'
response: 0xffffffa8
RPC executing UtaMsNetOpen
b'1600000002040000001602040000005311000100020400000000'
response: 0xffffffa8
RPC executing UtaMsCallCsInit
b'1600000002040000001602040000002411000100020400000000'
response: 0xffffffa8
RPC executing UtaMsCallPsInitialize
b'1600000002040000001602040000003a11000100020400000000'
response: 0xfffffff7
RPC executing UtaMsSsInit
b'1600000002040000001602040000002611000100020400000000'
response: 0xffffffa8
RPC executing UtaMsSimOpenReq
b'1600000002040000001602040000000111000100020400000000'
response: 0xffffffa8
RPC executing CsiFccLockQueryReq
b'1c00000002040000001c02040000018e11000101020411000101020400000000'
async_ack: 0x0
`
the script freeze at this point and no connexion.

What are theses error responses ?

Thank for your help

**Comment by tgxn** [comment]
Hey,

I would be helpful to have the full console output, including any intermediary messages, and what is the end-result code?

Otherwise, we could try with the latest repo changes and see if it has been resolved?
