### ISSUE TITLE
Network Manager doesn't recognize the connection, refuses to connect to VPN

### ISSUE THREAD

**Issue by alembiq** [xmm7360/xmm7360-pci#68]
As i can't see wwan connection in the networkmanager, i can't use network manager to connect to VPN, as it's convinced there is no connection :( 

Parrot OS (Debian based)
Lenovo X1 gen 7

**Comment by tgxn** [comment]
It is known that this PCI driver does not expose the network connection to NetworkManager.

There is a current PR open, https://github.com/xmm7360/xmm7360-pci/pull/66 that is meant to add support for this, however I have not been able to test it.

Perhaps you could check that code out and see if that functionality is working for you?

**Comment by alembiq** [comment]
tested and working :)

**Comment by deelerke** [comment]
I'm having the same issue.. is there a workaround? 
thanks
