### ISSUE TITLE
Works on X1 Carbon 6th Gen Ubuntu 20.04

### ISSUE THREAD

**Issue by griffintcash** [xmm7360/xmm7360-pci#97]
20KHCTO1WW
Clean install of Ubuntu 20.04 plus the dependencies

T-Mobile United States
APN=fast.t-mobile.com

**Comment by tgxn** [comment]
Cheers mate, Will add you to the Devices List soon :)

**Comment by papayarodeo** [comment]
Can confirm with european SIM. The script install worked flawlessly.

**Comment by Vbofyz** [comment]
Whatever i do, after "sudo python3 rpc/open_xdatachannel.py" it gives "response: 0xffffffff". Thinkpad x1 carbon gn6, Ubuntu 20.04. Does anyone know how to fix this?
